name: "watch-test-name"

services:
  web:
    build: .
    ports:
      - "8000:5000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code

  redis:
    image: "redis:alpine"
