name: Git Action Test

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: production
jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/mian' }}
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    env:
      DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
      PUBLISH_HOST: ${{ vars.PUBLISH_HOST }}

    steps:
      - run: echo "Deploying to production server on branch $DOCKER_KEY $PUBLISH_HOST"

      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.DOCKER_KEY }}
        run: |
          echo "$SUPER_SECRET"
