# This is a basic workflow to help you get started with Actions

name: git action workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["git-action"]

  workflow_dispatch:

env:
  DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/git-action' }}

    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying to production server on branch ${{ env.DOCKER_KEY }} ${{ vars.PUBLISH_HOST }}"
